-- _
-- Author: wldcmzy
-- DateCreated: 3/11/2024 6:16:16 PM
--------------------------------------------------------------
INSERT INTO Types			
(Type,																					Kind)	VALUES
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',												'KIND_TRAIT'),
('MODIFIERTYPE_CITIES_ADJUST_CAN_PURCHASE_DISTRICTS_SUPER_PURCHASER_MANSA_MUSA',		'KIND_MODIFIER');
--('MODIFIERTYPE_CITIES_ADJUST_CAN_FAITH_PURCHASE_DISTRICTS_MANSA_MUSA_SUPER_PURCHASER',	'KIND_MODIFIER');


INSERT INTO DynamicModifiers 
(ModifierType,																			CollectionType,					EffectType) VALUES 
('MODIFIERTYPE_CITIES_ADJUST_CAN_PURCHASE_DISTRICTS_SUPER_PURCHASER_MANSA_MUSA',		'COLLECTION_PLAYER_CITIES',		'EFFECT_ADJUST_CITY_CAN_PURCHASE_DISTRICTS');
--('MODIFIERTYPE_CITIES_ADJUST_CAN_FAITH_PURCHASE_DISTRICTS_MANSA_MUSA_SUPER_PURCHASER',	'COLLECTION_PLAYER_CITIES',		'EFFECT_ADJUST_CAN_FAITH_PURCHASE_DISTRICTS');

INSERT INTO Traits			
(TraitType,										Name,													Description)	VALUES
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'LOC_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_NAME',		'LOC_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_DESCRIPTION');

INSERT INTO LeaderTraits			
(LeaderType,			TraitType)	VALUES
('LEADER_MANSA_MUSA',	'TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER');



-- Faith Buy Buildings
---------------------------------------------------------------------------------------------------------------------

INSERT INTO TraitModifiers 
(TraitType,										ModifierId) VALUES 
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CITY_CENTER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HOLY_SITE'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CUMPUS'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_THEATER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_INDUSTRY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENTERTAINMENT'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_WATER_PARK'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_GOVERNMENT'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_DIPLOMACY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENCAMPMENT'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HARBOR'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_AERODROME'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_NEIGHBORHOOD');


INSERT INTO Modifiers 
(ModifierId,																ModifierType,												RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CITY_CENTER',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HOLY_SITE',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CUMPUS',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_THEATER',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_INDUSTRY',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENTERTAINMENT','MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_WATER_PARK',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_GOVERNMENT',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_DIPLOMACY',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENCAMPMENT',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HARBOR',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_AERODROME',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_NEIGHBORHOOD', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',	0,			0,			0,			NULL,					NULL);


INSERT INTO ModifierArguments 
(ModifierId,																Name,				Value) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CITY_CENTER',	'DistrictType',		'DISTRICT_CITY_CENTER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HOLY_SITE',	'DistrictType',		'DISTRICT_HOLY_SITE'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_CUMPUS',		'DistrictType',		'DISTRICT_CAMPUS'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_THEATER',		'DistrictType',		'DISTRICT_THEATER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_INDUSTRY',		'DistrictType',		'DISTRICT_INDUSTRIAL_ZONE'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENTERTAINMENT','DistrictType',		'DISTRICT_ENTERTAINMENT_COMPLEX'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_WATER_PARK',	'DistrictType',		'DISTRICT_WATER_ENTERTAINMENT_COMPLEX'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_GOVERNMENT',	'DistrictType',		'DISTRICT_GOVERNMENT'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_DIPLOMACY',	'DistrictType',		'DISTRICT_DIPLOMATIC_QUARTER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_ENCAMPMENT',	'DistrictType',		'DISTRICT_ENCAMPMENT'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_HARBOR',		'DistrictType',		'DISTRICT_HARBOR'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_AERODROME',	'DistrictType',		'DISTRICT_AERODROME'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_BUILDINGS_NEIGHBORHOOD', 'DistrictType',		'DISTRICT_NEIGHBORHOOD');


-- Faith Buy Units
---------------------------------------------------------------------------------------------------------------------

INSERT INTO TraitModifiers 
(TraitType,										ModifierId) VALUES 
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LANDCIVILIAN'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RECON'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_MELEE'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RANGED'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SIEGE'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ANTI_CAVALRY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LIGHT_CAVALRY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_HEAVY_CAVALRY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_FIGHTER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_BOMBER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_MELEE'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RANGED'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_CARRIER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RAIDER'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SUPPORT'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SPY'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ROCK_BAND'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_GIANT_DEATH_ROBOT');


INSERT INTO Modifiers 
(ModifierId,																		ModifierType,												RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LANDCIVILIAN',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RECON',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_MELEE',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RANGED',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SIEGE',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ANTI_CAVALRY',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LIGHT_CAVALRY',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_HEAVY_CAVALRY',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_FIGHTER',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_BOMBER',		'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_MELEE',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RANGED',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_CARRIER',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RAIDER',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SUPPORT',		'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SPY',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ROCK_BAND',		'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_GIANT_DEATH_ROBOT','MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL);


INSERT INTO ModifierArguments 
(ModifierId,																		Name,	Value) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LANDCIVILIAN',	'Tag',	'CLASS_LANDCIVILIAN'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RECON',			'Tag',	'CLASS_RECON'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_MELEE',			'Tag',	'CLASS_MELEE'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_RANGED',			'Tag',	'CLASS_RANGED'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SIEGE',			'Tag',	'CLASS_SIEGE'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ANTI_CAVALRY',	'Tag',	'CLASS_ANTI_CAVALRY'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_LIGHT_CAVALRY',	'Tag',	'CLASS_LIGHT_CAVALRY'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_HEAVY_CAVALRY',	'Tag',	'CLASS_HEAVY_CAVALRY'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_FIGHTER',	'Tag',	'CLASS_AIR_FIGHTER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_AIR_BOMBER',		'Tag',	'CLASS_AIR_BOMBER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_MELEE',	'Tag',	'CLASS_NAVAL_MELEE'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RANGED',	'Tag',	'CLASS_NAVAL_RANGED'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_CARRIER',	'Tag',	'CLASS_NAVAL_CARRIER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_NAVAL_RAIDER',	'Tag',	'CLASS_NAVAL_RAIDER'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SUPPORT',		'Tag',	'CLASS_SUPPORT'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SPY',			'Tag',	'CLASS_SPY'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_ROCK_BAND',		'Tag',	'CLASS_ROCK_BAND'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_GIANT_DEATH_ROBOT','Tag','CLASS_GIANT_DEATH_ROBOT');

/*
-- Gold Buy Units
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TraitModifiers 
(TraitType,										ModifierId) VALUES 
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SPY');


INSERT INTO Modifiers 
(ModifierId,																ModifierType,												RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_PROMOTION_CLASS_SPY',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',		0,			0,			0,			NULL,					NULL),
*/


/*
-- Faith & Gold Buy Districts
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TraitModifiers 
(TraitType,										ModifierId) VALUES 
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_GOLD_BUY_DISTRICTS'),
--('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS');
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS');

INSERT INTO Modifiers 
(ModifierId,														ModifierType,																			RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_GOLD_BUY_DISTRICTS',	'MODIFIERTYPE_CITIES_ADJUST_CAN_PURCHASE_DISTRICTS_SUPER_PURCHASER_MANSA_MUSA',			0,			0,			0,			NULL,					NULL),
--('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS',	'MODIFIERTYPE_CITIES_ADJUST_CAN_FAITH_PURCHASE_DISTRICTS_MANSA_MUSA_SUPER_PURCHASER',	0,			0,			0,			NULL,					NULL);
('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS',	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',												0,			0,			0,			NULL,					NULL);
INSERT INTO ModifierArguments 
(ModifierId,														Name,			Value) VALUES 
('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_GOLD_BUY_DISTRICTS',	'CanPurchase',	'1'),
--('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS',	'CanPurchase',	'1');
('MODIFIER_TRAIT_SUPER_PURCHASER_MANSA_MUSA_FAITH_BUY_DISTRICTS',	'ModifierId',	'CARDINAL_FAITH_PURCHASE_DISTRICT');
*/



-- Trade route desert hills add Gold
---------------------------------------------------------------------------------------------------------------------

INSERT INTO TraitModifiers 
(TraitType,										ModifierId) VALUES 
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN'),
('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN');
--('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN'),
--('TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER',		'MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN');

INSERT INTO Modifiers 
(ModifierId,																				ModifierType,															RunOnce,	Permanent,	NewOnly,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL',	0,			0,			0,			NULL,					NULL),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL',	0,			0,			0,			NULL,					NULL);
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL',	0,			0,			0,			NULL,					NULL),
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL',	0,			0,			0,			NULL,					NULL);

INSERT INTO ModifierArguments 
(ModifierId,																				Name,			Value) VALUES 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN',			'Amount',		'1'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN',			'Origin',		'1'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN',			'TerrainType',	'TERRAIN_DESERT'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_ORIGIN',			'YieldType',	'YIELD_GOLD'),
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN',	'Amount',		'1'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN',	'Origin',		'1'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN',	'TerrainType',	'TERRAIN_DESERT_HILLS'), 
('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_DESERT_HILL_ORIGIN',	'YieldType',	'YIELD_GOLD');
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN',	'Amount',		'1'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN',	'Origin',		'1'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN',	'TerrainType',	'TERRAIN_TUNDRA_HILLS'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_HILL_ORIGIN',	'YieldType',	'YIELD_FAITH'),
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN',			'Amount',		'1'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN',			'Origin',		'1'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN',			'TerrainType',	'TERRAIN_TUNDRA'), 
--('MODIFIER_TRAIT_LEADER_MANSA_MUSA_SUPER_PURCHASER_TRADE_ROUTE_GOLD_TUNDRA_ORIGIN',			'YieldType',	'YIELD_FAITH');